window.GUEST_GROUPS = {
  MAY001: { guests: ["Miriam"], guestCount: 1, table: "2" },
  MAY002: { guests: ["Sara"], guestCount: 1, table: "2" },
  MAY003: { guests: ["Soraya", "Gustavo", "Agustin", "Lourdes"], guestCount: 4, table: "2" },
  MAY004: { guests: ["Monica"], guestCount: 1, table: "2" },
  MAY005: { guests: ["Lucas", "Yamila"], guestCount: 2, table: "2" },
  MAY006: { guests: ["Rocio"], guestCount: 1, table: "4" },
  MAY007: { guests: ["Nazira"], guestCount: 1, table: "4" },
  MAY008: { guests: ["Belen"], guestCount: 1, table: "4" },
  MAY009: { guests: ["Lara"], guestCount: 1, table: "4" },
  MAY010: { guests: ["Romina"], guestCount: 1, table: "4" },
  MAY011: { guests: ["Gabriela"], guestCount: 1, table: "4" },
  MAY012: { guests: ["Giuliana", "Cecilia", "Gustavo"], guestCount: 3, table: "6" },
  MAY013: { guests: ["Melanie"], guestCount: 1, table: "6" },
  MAY014: { guests: ["Flavio"], guestCount: 1, table: "6" },
  MAY015: { guests: ["Maximiliano"], guestCount: 1, table: "6" },
  MAY016: { guests: ["Ileana"], guestCount: 1, table: "6" },
  MAY017: { guests: ["Elizabeth"], guestCount: 1, table: "6" },
  MAY018: { guests: ["Ezequiel"], guestCount: 1, table: "6" },
  MAY019: { guests: ["Carlos"], guestCount: 1, table: "6" },
  MAY020: { guests: ["Gaston"], guestCount: 1, table: "6" },
  MAY021: { guests: ["Romina", "Irina", "Liliana"], guestCount: 3, table: "8" },
  MAY022: { guests: ["Irene", "Erika"], guestCount: 2, table: "8" },
  MAY023: { guests: ["Ludmila"], guestCount: 1, table: "8" },
  MAY024: { guests: ["Tali", "Daniela"], guestCount: 2, table: "8" },
  MAY025: { guests: ["Gabriel"], guestCount: 1, table: "9" },
  MAY026: { guests: ["Matias"], guestCount: 1, table: "9" },
  MAY027: { guests: ["Sofia"], guestCount: 1, table: "9" },
  MAY028: { guests: ["Jael"], guestCount: 1, table: "9" },
  MAY029: { guests: ["Matias"], guestCount: 1, table: "9" },
  MAY030: { guests: ["Gabriel/Mayra"], guestCount: 1, table: "9" },
  MAY031: { guests: ["Eliana"], guestCount: 1, table: "9" },
  SEB001: { guests: ["Viviana", "Fernando", "Carlos"], guestCount: 3, table: "1" },
  SEB002: { guests: ["Nicolas", "Ester", "Camila"], guestCount: 3, table: "1" },
  SEB003: { guests: ["Carolina", "Julio", "Federico"], guestCount: 3, table: "1" },
  SEB004: { guests: ["Leandro", "Iara"], guestCount: 2, table: "1" },
  SEB005: { guests: ["Sofia", "Andres"], guestCount: 2, table: "3" },
  SEB006: { guests: ["Arian", "Vanesa"], guestCount: 2, table: "3" },
  SEB007: { guests: ["Mateo", "Julieta", "Andres", "Gabriela", "Lourdes", "Tomas"], guestCount: 6, table: "3" },
  SEB008: { guests: ["Ximena", "Bautista", "Emiliano"], guestCount: 3, table: "3" },
  SEB009: { guests: ["Ana mam\u00E1 de caro", "Carolina"], guestCount: 2, table: "4" },
  SEB010: { guests: ["Isabel mam\u00E1 de lauty", "Luis pap\u00E1 de lauty", "Lautaro"], guestCount: 3, table: "4" },
  SEB011: { guests: ["Paula"], guestCount: 1, table: "4" },
  SEB012: { guests: ["Graciela", "Cacho"], guestCount: 2, table: "5" },
  SEB013: { guests: ["Gustavo"], guestCount: 1, table: "5" },
  SEB014: { guests: ["Diego"], guestCount: 1, table: "7" },
  SEB015: { guests: ["Pablo"], guestCount: 1, table: "7" },
  SEB016: { guests: ["Nataniel"], guestCount: 1, table: "7" },
  SEB017: { guests: ["Agostina"], guestCount: 1, table: "7" },
  SEB018: { guests: ["Alan"], guestCount: 1, table: "7" },
  SEB019: { guests: ["Alex"], guestCount: 1, table: "7" },
  SEB020: { guests: ["Laia"], guestCount: 1, table: "7" },
  SEB021: { guests: ["Kevin"], guestCount: 1, table: "7" },
  SEB022: { guests: ["Brenda"], guestCount: 1, table: "3" }
};
